# Generated by Django 5.0 on 2023-12-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='aadhar_card_no',
            new_name='aadharcard_no',
        ),
    ]
