# Generated by Django 5.0 on 2023-12-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_rename_aadhar_card_no_person_aadharcard_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'femaile'), ('other', 'other')], max_length=10),
        ),
    ]
