# Generated by Django 5.0 on 2023-12-21 10:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadharcard_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
